spring:
  application:
    name: master-jpa

  devtools:
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

    net:
      sf:
        ehcache: debug